### ISSUE TITLE
Desk Connection Error: More Infomation required

### ISSUE THREAD

**Issue by AlexWHughes** [schw4rzlicht/twitch2ma#7]
**Is your feature request related to a problem? Please describe.**
Only for newer users (And some of us that forget)

**Describe the solution you'd like**
When the script quits due to not being able to connect I suggest changing the text to provide a suggestion such as 

" Could not connect to desk! Check Telnet is enabled, MA IP and Windows Firewall Exiting...

**Comment by schw4rzlicht** [comment]
This was added in `1.13.0-rc.4`. Please let me know if that's enough information or if I should add more. See changes here: d7c9103

**Comment by schw4rzlicht** [comment]
Fixed in `1.13.0`
